### ISSUE TITLE
Do not understand how to use

### ISSUE THREAD

**Issue by dcs3spp** [underyx/structlog-pretty#10]
Hi,

I am new to structlog and do not understand how to use this package to print multiline JSON string.

I am guessing that the JSONPrettifier accepts structlog bound field names to process?? Confused

Why do I get unexpected keyword argument event when I try the following explained below?

The following line raises the error in the listing below.

```logger.info("JSON Schema is =>", schema=mymodel.jschema_json())```

raises an error:

```bash
Traceback (most recent call last):
  File "/Users/really/Development/python/kafka/producer/main.py", line 21, in <module>
    asyncio.run(run(logger))
  File "/Users/really/.pyenv/versions/3.10.4/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/really/.pyenv/versions/3.10.4/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/really/Development/python/kafka/producer/producer/main.py", line 59, in run
    logger.info("Using JSON schema => ", schema=models.CreditDecision.schema_json())
  File "/Users/really/Development/python/kafka/producer/.venv/lib/python3.10/site-packages/structlog/_log_levels.py", line 124, in meth
    return self._proxy_to_logger(name, event, **kw)
  File "/Users/really/Development/python/kafka/producer/.venv/lib/python3.10/site-packages/structlog/_base.py", line 204, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
TypeError: PrintLogger.msg() got an unexpected keyword argument 'event'
make: *** [run] Error 1
```

I am configuring structlog as follows:

```python
import asyncio
import random

import structlog
import structlog_pretty

from producer.main import run

if __name__ == "__main__":

    structlog.configure(
        processors=[
            structlog_pretty.JSONPrettifier(["schema"]),
            structlog_pretty.SyntaxHighlighter({"schema": "json"}),
            structlog_pretty.MultilinePrinter(["schema"]),
        ]
    )
    logger = structlog.get_logger()

    random.seed()
    asyncio.run(run(logger))
```

**Comment by underyx** [comment]
Hi! I haven't used structlog in years so I cannot readily think of what the issue is. Does this error also happen when you don't have the structlog-pretty processors enabled?

**Comment by dcs3spp** [comment]
Hi,

After some tweaking I managed to get it working but it still confusing:

```
  structlog.configure(     
          processors=[         
              structlog.stdlib.add_log_level, 
              structlog.processors.StackInfoRenderer(),
              structlog.dev.set_exc_info,     
              structlog.processors.UnicodeDecoder(),
              structlog.processors.CallsiteParameterAdder(
                  parameters=[ 
                      CallsiteParameter.FILENAME,     
                      CallsiteParameter.FUNC_NAME,    
                      CallsiteParameter.LINENO,       
                  ]            
              ),
              structlog_pretty.JSONPrettifier(["schema"]),
              structlog_pretty.SyntaxHighlighter({"schema": "json"}),
              structlog_pretty.MultilinePrinter(["schema"]),
              structlog.dev.ConsoleRenderer(),
          ],
          wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
          logger_factory=structlog.PrintLoggerFactory(),
          cache_logger_on_first_use=True, 
      )
      logger = structlog.get_logger() 
  
      random.seed()
      asyncio.run(run(logger))                                 
```

I am guessing that the renderer has to be the last item in the list of the processors, e.g. ConsoleRenderer. I am also guessing that for the prettified printing need to specify field(s) on structlog context that will be rendered as json yaml etc. However, this is only guessing, unable to verify by any doeumentation! However, it seems to to be working. Maybe, developers could add additional info to documentation to confirm and add clairty for other developers to bring clairty and facilitate and attract usage!
